language: node_js
node_js: 10
matrix:
  include:
    - os: linux
      env:
        - X=xfb-run
    - os: windows
    - os: osx

name: $TRAVIS_OS_NAME
#before_script:
# - [ "$TRAVIS_OS_NAME" != "linux" ] || X=xfb-run
script:
  - echo npm run build
  - $X echo npm test --silent

jobs:
  include:
    - stage: test-deploy
      os: linux
      name: "Test job"
      script:
        - export TRAVIS_TAG=${TRAVIS_TAG:-$TRAVIS_BRANCH}
      deploy:
        provider: script
        script: echo test-deploy $TRAVIS_TAG
        skip_cleanup: true
