language: shell

install:
  - echo npm install

jobs:
  include:
    - name: Integration tests
      before_script: echo npm run build
      script: echo xvfb-run npm run ${TEST_TARGET:-test}
    - name: Package install tests
      before_script: echo npm run package
      script: echo xvfb-run npm run  test:package
       
