language: node_js
node_js: 10
os:
  - linux
  - windows
  - osx

install:
  - echo npm install
script:
  - echo npm run build
  - $(which xvfb-run) echo npm test --silent

jobs:
  include:
    - stage: test-deploy
      os: linux
      name: "Test job"
      script:
        - export TRAVIS_TAG=${TRAVIS_TAG:-$TRAVIS_BRANCH}
      deploy:
        provider: script
        script: echo test-deploy $TRAVIS_TAG
        skip_cleanup: true
