language: shell
matrix:
  include:
    - name: Linux
      env: TEST_SUITE=integration
    - name: "3.5 Integration Tests"
      env: TEST_SUITE=installation
script:
  - echo npm test

deploy:
  provider: script
  script: echo test-deploy $TRAVIS_TAG
  skip_cleanup: true
  on:
    branch: master
    condition: $TEST_SUITE = installation
 
   
