sudo: false
os: linux
#language: shell
#node_js: "10"

before_script:
 - export TRAVIS_TAG=v0.0.1

script:
 - echo hola
 
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  overwrite: true
  skip_cleanup: true
  prerelease: false
  on:
    tags: true
