language: node_js
node_js: 10
matrix:
  include:
    - name: Linux
      env: TEST_SUITE=integration
    - name: "3.5 Integration Tests"
      env: TEST_SUITE=installation
script:
  - echo npm test

jobs:
  include:
    - stage: test-deploy
      os: linux
      name: "Test job"
      script:
        - export TRAVIS_TAG=${TRAVIS_TAG:-$TRAVIS_BRANCH}
      deploy:
        provider: script
        script: echo test-deploy $TRAVIS_TAG
        skip_cleanup: true
   
