sudo: false
dist: xenial
cache: npm
language: node_js
node_js: 10
os:
  - linux
  - windows
  - osx
script:
 - echo "script"

jobs:
  include:
    - stage: test-job
      os: linux
      name: "Test job"
