sudo: false
os: windows
#language: node_js
#node_js: "10"
env:
  secure: "hH/iFAroTDk/biGo30CNSZcbn6oZrXsjcqkmpaElyX3Mctq0HM00KUWbohLOM17maJbxgXItzkT+pyXqmDLgJ7UkJNqLoLHDGDa7wmzJDQWX3qoX4q9Am69nV/zzoqDzIhWZLjd15JuRZh5m2YfsGuAPYwjXNoFQ0nEj+ZxUFOIlCHOdyqi1rQUGfL7mKZ9khrKNTPrXTVbZ07CoqMr4/YJbvT4zivxiqBXLIKBXOE0iBswMANl6DKxk9c1WkekBmlJXJr7LT9W/kWH2eX1OwUf9WciR8z1bPKGF5QUVgeeYZhbbVofETJT6hknSr3rrhsjFfP5Y0tV0pW4H0yePlxxjeXEICzV4khB5mrYO7fmkgDIgQckbi+cOGeVY/8uidCMfgJHHrsv2Ki7ZXAdRZAZqTXkvS7EucBkhpY8aOT7rNYoNuSFn80KxEx9HEM36LiFa22C2600hAe8ujT+oZ4+Z5ohGfpE/NQ85NYtcOVQroZGKBS59snDe7fXKNuLNIlUwCccn1Xuv+Cb9tO9NKFRxAxXF4yDJlyfrd9CpTkbdzOtB042mJA3j3JuKUDhLn46pV2nqPr94XFvp8xAxB0/6OCuM0Vn3JBruUo/eu5t7vrFunoRwK8zPV7RiDtsvO+kVRsGZOOzRHyZlPhodkefcwsKiayt2zoPGGCusH38="
script:
 - echo $SOMEVAR
 
