language: shell

env:
  global:
    - EXTENSION=perl-moose

install:
  - echo npm install
before_script:
  - echo npm run build
script:
  - echo xvfb-run npm ${TEST_TARGET:-test} --silent

jobs:
  include:
    - name: Package install tests
      before_script:
        - echo npm run package
      env:
        - TEST_TARGET=test:package
       
