sudo: false
os: linux
language: shell
#node_js: "10"

before_script:
 - export TRAVIS_TAG=v0.0.2

script:
 - echo hola
after_script:
  - echo "after script" 
before_deploy:
  - echo "before deploy" 
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: ".travis.yml"
  draft: false
  
after_success:
  - echo "after"
