sudo: false
dist: xenial
cache: npm
language: node_js
node_js: 10
env:
  global:
    - TRAVIS_TAG=${TRAVIS_TAG:-$TRAVIS_BRANCH}
os:
  - linux
  - windows
  - osx
before_script:
  - echo $TRAVIS_TAG
script:
 - echo "script"


before_deploy: "echo before deploy"
deploy:
  provider: script
  script: echo deploy

jobs:
  include:
    - stage: test-job
      os: linux
      name: "Test job"
